
/**
 * Generated by CreatorEngine
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_venturiController from "./scripts/venturiController";
import * as scripts_box from "./scripts/box";

export const scriptsMap = {
    "scripts/venturiController.ts": scripts_venturiController,
	"scripts/box.ts": scripts_box
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
